// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMbzEMSkvQ2hV1TsH3ny8fHCC_hRSgu4',
    appId: '1:784815988556:web:6fd5344d2e3acbe0adb9e9',
    messagingSenderId: '784815988556',
    projectId: 'ibecouleveilkidv2',
    authDomain: 'ibecouleveilkidv2.firebaseapp.com',
    storageBucket: 'ibecouleveilkidv2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgrt83-W0dVMMnbQZOth_IOSwy5Nrsug',
    appId: '1:784815988556:android:057f9dbd029dc58badb9e9',
    messagingSenderId: '784815988556',
    projectId: 'ibecouleveilkidv2',
    storageBucket: 'ibecouleveilkidv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49P-NwXg_icWFd0f8mIq3ffTcjDa0rhU',
    appId: '1:784815988556:ios:ec06f11543a9236aadb9e9',
    messagingSenderId: '784815988556',
    projectId: 'ibecouleveilkidv2',
    storageBucket: 'ibecouleveilkidv2.firebasestorage.app',
    iosBundleId: 'com.example.eveilenfant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49P-NwXg_icWFd0f8mIq3ffTcjDa0rhU',
    appId: '1:784815988556:ios:ec06f11543a9236aadb9e9',
    messagingSenderId: '784815988556',
    projectId: 'ibecouleveilkidv2',
    storageBucket: 'ibecouleveilkidv2.firebasestorage.app',
    iosBundleId: 'com.example.eveilenfant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMbzEMSkvQ2hV1TsH3ny8fHCC_hRSgu4',
    appId: '1:784815988556:web:201e24d0f6eef3edadb9e9',
    messagingSenderId: '784815988556',
    projectId: 'ibecouleveilkidv2',
    authDomain: 'ibecouleveilkidv2.firebaseapp.com',
    storageBucket: 'ibecouleveilkidv2.firebasestorage.app',
  );
}
