// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-gx0xd4XOVZzYD7szX_KaQUI5h2yw-k',
    appId: '1:847684786362:android:b2f7d558f57b9b6c870a83',
    messagingSenderId: '847684786362',
    projectId: 'ibecoul',
    storageBucket: 'ibecoul.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdpyUO27ORr1pxaqtispz9i2F8W8j6gwM',
    appId: '1:847684786362:ios:7b0860daf4078604870a83',
    messagingSenderId: '847684786362',
    projectId: 'ibecoul',
    storageBucket: 'ibecoul.firebasestorage.app',
    iosBundleId: 'com.example.eveilkid',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNdNNSy_XHOvrbdHrwn8O5popmoAx6RUA',
    appId: '1:847684786362:web:6b50c6f1070dbe12870a83',
    messagingSenderId: '847684786362',
    projectId: 'ibecoul',
    authDomain: 'ibecoul.firebaseapp.com',
    storageBucket: 'ibecoul.firebasestorage.app',
  );
}
