// lib/features/parent/presentation/pages/ajouter_enfant.dart

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/AppPadding.dart';
import '../../../../core/constants/AppRadius.dart';
import '../../../../core/constants/AppSpacing.dart';
import '../../../../core/constants/AppTextStyles.dart';
import '../../../../shared/widgets/app_dialogs.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../../shared/widgets/app_text_field.dart';
import '../../../../shared/widgets/app_date_picker.dart';
import '../../../../shared/widgets/app_dropdown.dart';
import '../../../../shared/widgets/app_avatar.dart';
import '../../models/parent_model.dart';
import '../../providers/parent_provider.dart';
import '../../../auth/providers/auth_provider.dart';

class AjouterEnfantPage extends ConsumerStatefulWidget {
  const AjouterEnfantPage({super.key});

  @override
  ConsumerState<AjouterEnfantPage> createState() => _AjouterEnfantPageState();
}

class _AjouterEnfantPageState extends ConsumerState<AjouterEnfantPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  DateTime _selectedDate = DateTime.now().subtract(const Duration(days: 365 * 4));
  String _selectedGenre = 'NON_SPECIFIE';
  String? _avatarUrl;
  bool _isLoading = false;

  final List<Map<String, String>> _genres = [
    {'value': 'GARCON', 'label': 'Garçon'},
    {'value': 'FILLE', 'label': 'Fille'},
    {'value': 'NON_SPECIFIE', 'label': 'Non spécifié'},
  ];

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final authState = ref.read(authProvider);
    final userId = authState.utilisateur?.utilisateurId ?? '';

    setState(() => _isLoading = true);

    final newChild = EnfantModel(
      enfantId: '', // Will be generated by Firestore if handled by repository
      utilisateurId: userId,
      nom: _nameController.text.trim(),
      dateNaissance: _selectedDate,
      genre: _selectedGenre,
      avatarUrl: _avatarUrl,
    );

    try {
      await ref.read(parentNotifierProvider.notifier).ajouterEnfant(newChild);

      if (mounted) {
        AppDialogs.showSnackBar(
          context: context,
          message: '${newChild.nom} a été ajouté avec succès !',
        );
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        AppDialogs.showSnackBar(
          context: context,
          message: 'Erreur: $e',
          isError: true,
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text('Ajouter un enfant', style: AppTextStyles.headingSmall),
      ),
      body: SingleChildScrollView(
        padding: AppPadding.screen,
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              AppSpacing.verticalLg,
              Center(
                child: Stack(
                  children: [
                    AppAvatar(
                      imageUrl: _avatarUrl,
                      radius: 50,
                      defaultIcon: Icons.face_rounded,
                    ),
                    Positioned(
                      bottom: 0,
                      right: 0,
                      child: CircleAvatar(
                        backgroundColor: AppColors.primary,
                        radius: 18,
                        child: IconButton(
                          icon: const Icon(Icons.camera_alt, size: 18, color: Colors.white),
                          onPressed: () {
                            // TODO: Implement image picker
                            AppDialogs.showSnackBar(context: context, message: 'Sélecteur d\'image bientôt disponible');
                          },
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              AppSpacing.verticalXl,

              AppTextField(
                controller: _nameController,
                label: 'Prénom de l\'enfant',
                hintText: 'Ex: Nour, Ilyas, Mariam...',
                prefixIcon: Icons.person_outline,
                validator: (val) {
                  if (val == null || val.trim().isEmpty) {
                    return 'Veuillez renseigner le prénom de l\'enfant';
                  }
                  return null;
                },
              ),
              AppSpacing.verticalMd,

              AppDatePicker(
                label: 'Date de naissance',
                selectedDate: _selectedDate,
                onDateSelected: (date) {
                  setState(() => _selectedDate = date);
                },
              ),
              AppSpacing.verticalMd,

              const Text(
                'Genre',
                style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: AppColors.textPrimary),
              ),
              AppSpacing.verticalXs,
              Row(
                children: _genres.map((genre) {
                  final isSelected = _selectedGenre == genre['value'];
                  return Padding(
                    padding: const EdgeInsets.only(right: 8.0),
                    child: ChoiceChip(
                      label: Text(genre['label']!),
                      selected: isSelected,
                      onSelected: (selected) {
                        if (selected) setState(() => _selectedGenre = genre['value']!);
                      },
                      selectedColor: AppColors.primary.withOpacity(0.2),
                      labelStyle: TextStyle(
                        color: isSelected ? AppColors.primary : AppColors.textSecondary,
                        fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                      ),
                    ),
                  );
                }).toList(),
              ),
              AppSpacing.verticalXxl,

              AppButton(
                text: 'Enregistrer l\'enfant',
                icon: Icons.check,
                isLoading: _isLoading,
                onPressed: _submit,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
